# Copyright 2018 Atelier Disko. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

language: go

go:
  - 1.11

env:
  - GO111MODULE=on

matrix:
  fast_finish: true

notifications:
  email: false

sudo: false

before_install:
  - go get github.com/twitter/go-bindata/...

# Auto upload release artificats to GitHub, when a new release is tagged. Build
# releases with latest Go version only.
before_deploy:
  - make dist

deploy:
  provider: releases
  api_key:
    secure: qexa8lPvk6+ECLHW123jKIsfACG1ptqj3agClj7g5V0RjKumivOqn2D6R/uPD9pTDrdV+XrBR1ObUe56X10ukN9Vx5P/4OwEj+Bk6qcvT+PPn4fuSg91la0npRL0yWKUIvZceuAyyqF5mnsT4bB1BoELZ84dOncFXPxOgjFuInjbXV8L8/60O29JpuTVNduVfLWg0zL4PhTPAFlSIA8zyMyUxIl6XBQjoKgPHB/aTahJxfC4KvRbr+UnAgu9LoUE4cjpZ5SrsRyh/v4PiPKwAN3WNfpCWT8KVPTNaaOkfQLBHx8IJXzkeUr7zqBndFQAFHlgCL1rRYFl2uH8eHPTuoEokgCMMd60JfNooIUS31SYl05BYGG4LSLxYoM3OZa4PWJGFS20ZNV7nBGovj00bOf5LBBnO5CjN5AJk//m0s2W7Var/T1doT9ESbAdkSRPTS+/GBNbQPUV/1GmgJABUqiuxPoWB8mH4MczNGXdUkC+QgIaMSDwI42M6Or3p2GxsMvtFDWZCdB25Sja97BNEV2Xji6PX5QMyZGKBwZLsleNOVC/GNYRojm7k5Ru6LcyE5sFSsMvK+I3wu7/jf7AQjv58RE2WSrz6+FmhbGOOi5n7YzCsGWFeVs1Xp9A+631sH8UZ37F466Hf8ECXWreKzFq0EN7Njv/wpIV76OCiLc=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tag: true
    repo: atelierdisko/dsk
    condition: $TRAVIS_GO_VERSION =~ ^1\.11\.[0-9]+$